export const ticketDetails = [
  {
    id: 0,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 1,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 2,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 3,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 4,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 5,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 6,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 7,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 8,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 9,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
  {
    id: 10,
    ticketNo: "123232",
    ticketDescription: "unable to do cash Withdraw",
    category: "Enquiry",
    raisedBy: "Ramesh Gupta",
    label: "new",
    createdOn: "2023-12-12T02:00:00.000Z",
  },
];

export const ticketStatusDetails = [
  {
    label: "Medium",
    ticketDescription: "Customer Support",
    category: "Enquiry",
    agentName: "Jonh Smith",
    ticketStatus: "Open",
  },
];
